//auth
export const AUTH_CLIENT_AUTH = 'AUTH_CLIENT_AUTH';
export const AUTH_CLIENT_UNAUTH = 'AUTH_CLIENT_UNAUTH';
export const AUTH_USER_AUTH = 'AUTH_USER_AUTH';
export const AUTH_USER_UNAUTH = 'AUTH_USER_UNAUTH';
export const AUTH_USER_SESSIONEXP = 'AUTH_USER_SESSIONEXP';
export const AUTH_SET_REDIRECT_PATH = 'AUTH_SET_REDIRECT_PATH';
export const AUTH_ERROR_SET = 'AUTH_ERROR_SET';

//user
export const USER_INFO_SET = 'USER_INFO_SET';
export const USER_ADD = 'USER_ADD';
export const USER_LIST = 'USER_LIST';
export const USER_GET = 'USER_GET';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_DELETE = 'USER_DELETE';

//agency
export const AGENCY_LIST = 'AGENCY_LIST';
export const AGENCY_GET = 'AGENCY_GET';
export const AGENCY_ADD = 'AGENCY_ADD';
export const AGENCY_ADD_DO = 'AGENCY_ADD_DO';
export const AGENCY_UPDATE = 'AGENCY_UPDATE';
export const AGENCY_UPDATE_DO = 'AGENCY_UPDATE_DO';
export const AGENCY_DELETE = 'AGENCY_DELETE';

//report
export const REPORT_LIST = 'REPORT_LIST';
export const REPORT_ADD = 'REPORT_ADD';

//user
export const HOTEL_LIST = 'HOTEL_LIST';
export const HOTEL_GET = 'HOTEL_GET';
export const HOTEL_UPDATE = 'HOTEL_UPDATE';

//provider
export const PROVIDER_LIST = 'PROVIDER_LIST';
export const PROVIDER_GET = 'PROVIDER_GET';
export const PROVIDER_ADD = 'PROVIDER_ADD';
export const PROVIDER_ADD_DO = 'PROVIDER_ADD_DO';
export const PROVIDER_UPDATE = 'PROVIDER_UPDATE';
export const PROVIDER_UPDATE_DO = 'PROVIDER_UPDATE_DO';
export const PROVIDER_DELETE = 'PROVIDER_DELETE';

//activepropertylists
export const ACTIVEPROPERTYLIST_LIST = 'ACTIVEPROPERTYLIST_LIST';
export const ACTIVEPROPERTYLIST_GET = 'ACTIVEPROPERTYLIST_GET';
export const ACTIVEPROPERTYLIST_ADD = 'ACTIVEPROPERTYLIST_ADD';
export const ACTIVEPROPERTYLIST_ADD_DO = 'ACTIVEPROPERTYLIST_ADD_DO';
export const ACTIVEPROPERTYLIST_UPDATE = 'ACTIVEPROPERTYLIST_UPDATE';
export const ACTIVEPROPERTYLIST_UPDATE_DO = 'ACTIVEPROPERTYLIST_UPDATE_DO';
export const ACTIVEPROPERTYLIST_DELETE = 'ACTIVEPROPERTYLIST_DELETE';

//suppliermap
export const SUPPLIERMAP_LIST = 'SUPPLIERMAP_LIST';
export const SUPPLIERMAP_GET = 'SUPPLIERMAP_GET';
export const SUPPLIERMAP_ADD = 'SUPPLIERMAP_ADD';
export const SUPPLIERMAP_ADD_DO = 'SUPPLIERMAP_ADD_DO';
export const SUPPLIERMAP_UPDATE = 'SUPPLIERMAP_UPDATE';
export const SUPPLIERMAP_UPDATE_DO = 'SUPPLIERMAP_UPDATE_DO';
export const SUPPLIERMAP_DELETE = 'SUPPLIERMAP_DELETE';

//mapping
export const GET_MAPPING = 'GET_MAPPING';
export const MAPPING_LIST = 'MAPPING_LIST';
export const SAVE_MAPPING = 'SAVE_MAPPING';
export const MAPPING_DELETE = 'MAPPING_DELETE';
